.gitmodules, src/plugins.ts
The syntax of the plugin is a bit messy because my inexperience with typescript, but it works exactly as it should when disabled and enabled.
You might want to review the order of the toggles. I put it at the bottom.
In short what the plugin does is enable the user to right click the expression's settings bubble instead of having to long hold.
=> Plugin right click tray

src/globals/window.ts
This allows them to be passed around before `window.Calc` or 
`window.require` are defined.
Fixes #59 and fixes #65.
=> 🐛 Wrap `Calc` and `desmosRequire` in Proxies

public/manifest.json, public/net_request_rules.json, public/net_request_rules.md
This avoids the warning "SharedArrayBuffer will require cross-origin 
isolation as of M91, around May 2021."
Resolves 
https://github.com/jared-hughes/desmodder-video-creator/issues/3
=> 🐛 Enable cross-origin resource protection

src/desmodder.ts, src/plugins/builtin-settings/index.ts, src/utils.tsx
They apply temporarily until page refresh or until the the options are re-toggled within the extension settings
Fixes part, but not all, of #101
=> 🐛 Override settings from query parameters

src/plugins/builtin-settings/index.ts
Broken in #144. Now extension storage correctly affects the settings,
but they *can* be overriden by query parameters
=> 🐛 Fix builtin-settings extension storage being ignored

src/plugins/wolfram2desmos/wolfram2desmos.ts
Removed indexing of `input` to prevent possible crash
=> Fixed lookahead crash error

src/desmodder.ts, src/parsing/parsenode.ts, src/parsing/traverse.ts, src/plugins/find-replace/backend.ts, src/utils/depUtils.ts
Fixes #103 and some rare issues. But this mainly sets up for further parse tree stuff. Partially resolves #39
=> Use the parse tree for identifier→* replacements

src/plugins/wolfram2desmos/wolfram2desmos.ts
Previously, `abs(x - y) + abs(abs(x + y + (x + abs(x))/2) - (x + abs(x))/2) = 1` did not work properly. This commit fixes that.
Beware that `|x|` notation is still janky. For the best results, use `abs(x)` only.
=> Fixed critical `abs(x)` error

src/globals/Calc.ts, src/main/Controller.ts, src/plugins/GLesmos/index.ts, src/plugins/duplicate-hotkey/index.ts, src/plugins/show-tips/tips.ts
Show the warning when GLesmos is disabled, but the user opens a graph with a GLesmos-enabled expression.
=> Disable GLesmos by default, and show a warning

src/plugins/wolfram2desmos/wolfram2desmos.ts
[] brackets like `a[2]` will become fancier +
trig exponents work correctly now.
=> [] bracket support + function exponents fix'd

src/parsing/IR.ts, src/plugins/GLesmos/Controller.ts, src/plugins/GLesmos/builtins.ts, src/plugins/GLesmos/emitChunkGL.ts, src/plugins/GLesmos/glesmosCanvas.ts, src/plugins/GLesmos/outputHelpers.ts, src/utils/depUtils.ts
There are still quite a few rough edges:
- list length must be determinable at compile time.
- This *could* be worked around by obtaining upper bounds for lists (e.g. requiring list slices to always decrease the list length), then storing filtered shorter lists in a long array with a separate variable for the length. This would open up the possibility of the `unique` function, list filters, and some others.
- The `sort` function is pretty slow, which is to be expected. As such, I haven't implemented `median` and the other quantiles
- The quantile functions *could* be sped up (compared to a simple index into a sort) by implementing quickselect
- The `shuffle` function, the `random` function, and a few others have not been implemented because they should not occur at GL compile time (either …
=> Allow lists in GLesmos

package-lock.json, package.json, webpack.config.js
This fixes the GH action errors. This loader turned out to be unnecessary (`asset/inline` is equivalent), and it caused the errors because its peer is webpack@4.x, and we're on webpack@5.x (which supports asset/inline)
=> Remove base64-inline-loader

src/plugins/find-replace/ReplaceBar.less, src/plugins/find-replace/ReplaceBar.tsx, src/plugins/find-replace/View.ts, src/plugins/text-mode/Controller.ts, src/preload/moduleOverrides/instancehotkeys.ts
- Fix Ctrl+F hotkey when expressions list is not selected
- Prevent expression search while inside text mode
- Move "replace all" button to same line as replace box
=> Fix find-replace styles and Ctrl+F hotkey

src/preload/moduleOverrides/expression-menus__fill.ts
Previous label was "Rendered with GLesmos", which showed even when the slider was disabled. Re-added and renamed to "Render with GLesmos".
Closes #424
=> 🌐: Add localised aria-label to GLesmos toggle

localization/en.ftl, src/plugins/performance-info/PerformanceView.tsx, src/plugins/performance-info/View.ts
"ms" was left as a literal because it's an SI unit
=> 🌐: Fully localise performance-info plugin

src/plugins/GLesmos/glesmosCanvas.ts
Shaders are now cached instead of being remade every time the canvas is rerendered.
This is the same as the previous PR, but without the "frame spreading" feature.
=> Glesmos shader cache fix

localization/en.ftl, src/globals/Calc.ts, src/plugins/wakatime/config.ts, src/plugins/wakatime/heartbeat.ts, src/plugins/wakatime/index.ts, src/preload/content.ts
- Modifies the WakaTime plugin to more closely match other plugins. It now properly follows https://wakatime.com/help/creating-plugin so AFK time will not be counted (heartbeats are only sent as a result of user interaction).
- Adds an option to split each graph into its own project (current behaviour) with the default being to store all graphs as one project ("Desmos Project"). Strongly recommended by Heavenira. (Resolves #450)
- Fixes a few miscellaneous bugs related to the plugin. (Resolves #451)
=> Refactor WakaTime plugin

src/preload/moduleOverrides/hide-errors.replacements, src/preload/replacementHelpers/applyReplacement.ts, src/preload/replacementHelpers/parse.ts, src/preload/replacementHelpers/tokenize.ts
- Get rid of carriage returns in replacements
- Allow multiple replacements in one block
- Keep track of invalidated ranges
- Give line numbers on tokenizer errors
- Include spaces in "pattern not found" error
=> Improve replacements

public/chrome/manifest.json, public/chrome/net_request_rules.json, public/firefox/manifest.json, src/background.ts
Now, DesModder works on https://delta.desmos.com as well as any other
subdomain.
This is easy to get wrong ([last patch when this went wrong](https://github.com/DesModder/DesModder/commit/c3a175bc484060301e134a6bbc02f0969fd57f7b)),
so I have checked, for both Firefox and Chrome:
This might have just been wrong the last time because it filtered for
`https://*.desmos.com/*`; now, we filter for
`https://*.desmos.com/calculator*` instead, which should not false-
positive any subdomains for enabling COEP and COOP.
=> Enable DesModder for all subdomains

src/preload/moduleOverrides/glesmos.replacements
Patches the outdated replacements in https://github.com/DesModder/DesModder/issues/494 and makes DesModder load again.
This should probably be merged ASAP to restore partial functionality.
We can investigate what (if anything) this PR breaks later.
=> tiny hotfix

esbuild.mjs, src/components/Toggle.less, src/i18n/i18n-core.ts, src/main/Controller.ts, src/panic/html.d.ts, src/panic/panic.html, src/panic/panic.ts, src/preload/content.ts, src/preload/moduleOverrides/core.replacements, src/preload/moduleOverrides/extra-expression-buttons.replacements, src/preload/moduleOverrides/find-replace.replacements, src/preload/moduleOverrides/glesmos.replacements, src/preload/moduleReplacements.ts, src/preload/replacementHelpers/applyReplacement.ts, src/preload/replacementHelpers/parse.ts, src/preload/script.ts, src/script.ts, src/utils/messages.ts, src/utils/utils.ts
Relates to #480, but there is still work to be done to finish the ideas in that issue.
- Show panic messages (non-functional)
- Require replacements to have valid plugin names
- Add actual forced plugin disabling
- Remove accidentally-committed files
- Prevent enabling force-disabled plugins
- Allow hiding loading error manager
- Remove try-catch around main init
=> Fail gracefully on replacements errors

localization/en.ftl, src/globals/Calc.ts, src/plugins/video-creator/Controller.ts, src/plugins/video-creator/backend/capture.ts, src/plugins/video-creator/components/CaptureMethod.tsx
Resolves #508
- Support ticking all playing sliders simultaneously
- Add UI for changing time step
- Avoid stalling on small slider tick sizes
- Handle cancelling in the middle of ticks capture
- Handle UI when action-capture pauses sliders
=> Capture simultaneous sliders in GLesmos

src/plugins/GLesmos/Controller.ts, src/plugins/GLesmos/exportAsGLesmos.ts, src/plugins/GLesmos/glesmosCanvas.ts, src/plugins/GLesmos/shaders.ts, src/preload/moduleOverrides/glesmos.replacements
When outlines are disabled for an entire group of list implicits (whether it be via 0 width, 0 alpha, or the toggle switch), GLesmos will now use a faster single-pass fill shader.
=> GL perf improvements

localization/en.ftl, src/main/Controller.ts, src/main/metadata/interface.ts, src/main/metadata/manage.ts, src/plugins/GLesmos/glesmos.less, src/preload/moduleOverrides/glesmos.replacements
This only applies to GLesmos inequalities like `sin(xy)>0`, and not equalities like `sin(xy)=0` since equalities could not be plotted before the outlines update.
The primary purpose of this change is to ensure that graphs created pre-outlines would not suddenly get much slower post-outlines. Adding a new confirmation check avoids the stateful mess of the alternative (version migration, changing the interpretation of the lines property, etc.).
A secondary purpose to this update is to show a little message before people enable lines. This has minor utility and only appears for inequalities.
=> Add confirmation for GLesmos lines

package.json, scripts/test-jest.sh, src/plugins/text-mode/aug/AugLatex.ts, src/plugins/text-mode/aug/augNeedsParens.ts, src/plugins/text-mode/aug/augToRaw.ts, src/plugins/text-mode/aug/rawToAug.ts, src/plugins/text-mode/aug/roundTripParse.test.ts, src/plugins/text-mode/down/TextAST.ts, src/plugins/text-mode/down/astToAug.ts, src/plugins/text-mode/up/astToText.ts, src/plugins/text-mode/up/augToAST.ts
Adds and uses `augNeedsParens` to determine if parentheses are needed on the emit of an expression to raw. The previous behavior was effectively always returning true. Now, we convert many cases to false, making ronwnor slightly happier.
Also download calculator_desktop before tests, to be able to test against Desmos's parser.
=> Reduce parens emitted to raw

src/components/desmosComponents.ts, src/globals/Calc.ts, src/globals/window.ts, src/plugins/text-mode/LanguageServer.ts, src/plugins/text-mode/index.ts, src/plugins/text-mode/modify.ts, src/plugins/text-mode/view/editor.less, src/plugins/text-mode/view/editor.ts, src/plugins/text-mode/view/plugins/StyleCircle.less, src/plugins/text-mode/view/plugins/footerWidget.less, src/plugins/text-mode/view/plugins/footerWidget.ts, src/plugins/text-mode/view/plugins/styleCircles.ts, src/preload/moduleOverrides/text-mode.replacements
- Show expression footers in text mode
- Check for relevant event types later
- Avoid dispatch-in-dispatch from setState in Text Mode (unrelated fix)
- Fix style of slider arrows (really a style circles fix)
=> Add footers in Text Mode

src/preload/moduleOverrides/better-evaluation-view.replacements
This code was deleted a while ago in mistake (it failed to replace successfully, and I thought it wasn't needed because I didn't check lists).
Props to @FenyLabs for spotting the mistake.
=> Distinguish NaN, +∞, -∞ in lists.

src/plugins/intellisense/index.tsx, src/plugins/pillbox-menus/components/Menu.tsx
- Intellisense no longer prevents Tab from working when it isn't open.
- Intellisense is now listed in the core plugin list in the settings menu.
=> Intellisense: Fixed Tab issue + Added to Core Plugins

src/plugins/intellisense/index.tsx, src/plugins/video-creator/components/CaptureMethod.tsx, src/plugins/video-creator/components/MainPopup.tsx
The intellisense menu no longer opens in inputs that don't support it. This is accomplished by using two CSS classes `yes-intellisense` and `no-intellisense`. `yes-intellisense` enables intellisense in its descendants that are MathQuill inputs. `no-intellisense` disables intellisense in its MathQuill input descendants. The first ancestor encountered determines whether intellisense is enabled or not. That way, these can override each other as you go down the hierarchy.
By default, intellisense is enabled in all MathQuill inputs except for those in the settings menu. I've also added `no-intellisense` and `yes-intellisense` tags to the Video Creator menu as appropriate.
=> Intellisense: No more intellisense in arithmetic-only MathQuill inputs

src/plugins/compact-view/compact.less, src/plugins/multiline/index.ts
- AuthorFeatures popup no longer causes overflow in Compact View.
- "X" button no longer overflows with small font sizes.
- Evaluations are no longer multilined to prevent them flying off the expression they're from.
Fixes #643
=> Compact View/Multiline: Various CSS Fixes

src/plugins/text-mode/down/textToRaw.ts
Docstring math segments no longer allow partial Text Mode parses and instead fall back to LaTeX when a full Text Mode parse isn't possible.
=> Intellisense: Docstring Math Segments now correctly falls back to LaTeX

src/plugins/intellisense/latex-parsing.tsx
This graph (and other ones like it with lots of nesting) crashed with Intellisense enabled: https://www.desmos.com/calculator/kqe1c4xuoi
This PR fixes this.
=> Intellisense: Fixed intellisense lag with deeply-nested expressions

src/plugins/intellisense/docs/README.md
Intellisense documentation accidentally had the old `@param=PARAMNAME` syntax when now it's been changed to `@param PARAMNAME`
=> Intellisense: Fixed documentation

scripts/eslint-rules/no-reach-past-exports.js
The previous code worked everywhere (except Windows) by serendipity because JS uses forward slashes. Now, actually resolve those paths.
Fixes #669
=> Use absolute allowed paths in no-reach-past-exports

src/plugins/intellisense/intellisense.int.test.ts
Turns out I *do* need the delays in the tests, otherwise they seem to fail most of the time. Conversely, I ran it three times in a row with the delays and it worked every single time.
=> Intellisense: Add back delays in tests

src/plugins/debug-mode/index.ts, src/plugins/text-mode/index.ts, src/plugins/text-mode/view/editor.less, src/plugins/text-mode/view/editor.ts, src/plugins/text-mode/view/plugins/stmtNumbers.ts
There might currently be no way to get a difference between IDs and indices while in text mode. 
But merging with https://github.com/DesModder/DesModder/pull/695 allows for actually testing this code:
Fixes #693
=> Show IDs in Text Mode with Debug Mode enabled

src/plugins/custom-mathquill-config/index.ts
(sorry fireflame i swear this was an accident)
Skips over static MathQuill fields when applying greek letter injections. Caused error to be thrown when a table was present in the expression list.
=> Custom MQ Config Fixes

src/plugins/intellisense/index.tsx, src/plugins/intellisense/intellisense.int.test.ts
Steps to reproduce:
- Start writing `c(x)=rgb(x,x,x)`
- Before commit: After writing the first comma, the cursor would move after the (ghost) close paren. After commit: the cursor stays where it is
=> Don't auto-subscript length-1 identifiers

localization/en.ftl, src/plugins/custom-mathquill-config/config.ts, src/plugins/custom-mathquill-config/custom-mathquill-config.less, src/plugins/custom-mathquill-config/index.ts
The default spacing felt a bit excessive, this PR adds an option to reduce that
=> Add custom-mathquill-config option to reduce spacing around "f"

localization/en.ftl, src/plugins/text-mode/lezer/completions.ts, src/plugins/text-mode/modify.ts, src/plugins/text-mode/view/editor.ts, src/plugins/text-mode/view/plugins/FormatPanel.less, src/plugins/text-mode/view/plugins/FormatPanel.tsx, src/plugins/text-mode/view/plugins/footerWidget.ts, src/plugins/text-mode/view/plugins/formatPanelPlugin.ts, src/plugins/text-mode/view/statementIntersection.unit.test.ts, text-mode-core/TextAST/index.ts, text-mode-core/index.ts, text-mode-core/tests/roundTripEmit.unit.test.ts, text-mode-core/tests/roundTripParse.unit.test.ts, text-mode-core/up/astToText.ts, text-mode-core/up/augToAST.ts, text-mode-core/up/augToText.ts, text-mode-core/up/needsParens.ts, text-mode-core/up/rawToText.ts
- `astToText` and related functions now take `TextEmitOptions`, which allows disabling spaces and newlines
- Adds a "Format" button that also lets you toggle "Spaces" and "Newlines" (If spaces is TRUE, then newlines is forced to TRUE)
- Places footers at the end of lines, so they don't interject into the middle of lines
=> Add emit config to remove spaces and newlines

src/plugins/pillbox-menus/components/PillboxContainer.less, src/plugins/pillbox-menus/components/PillboxContainer.tsx, src/plugins/pillbox-menus/pillbox-menus.replacements
Removed a replacement that didn't seem to matter anymore (the container no longer has a predicate) and added a new class responsible for pillbox sizing.
=> Fix pillbox buttons

localization/en.ftl, src/plugins/index.ts, src/plugins/multiline/config.ts, src/plugins/multiline/index.ts, src/plugins/multiline/verticalify.ts, src/plugins/pillbox-menus/components/Menu.less, src/plugins/pillbox-menus/components/Menu.tsx
Adds a setting to the Multiline plugin that converts all instances of three consecutive spaces `   ` to newlines. Also adds a setting to disable the default automatic multilining behavior. In other words, stuff like this is now possible:
=> Multiline: Spaces to Newlines

src/plugins/set-primary-color/index.ts
Was ported backwards from the ternary `isGeometry ? [...] : [...]` (which was confusing because "calculator" should be listed first typically, and "geometry" second)
=> Fix calculator/geometry swap in set-primary-color

src/globals/Calc.ts, src/plugins/better-navigation/index.ts
Before, Ctrl+Backspace and Ctrl+Delete wouldn't cause the graph to update (e.g. if you type out `x` and hit `Ctrl+Backspace`, a line will still be drawn). I've fixed this by simulating typing out an empty string with MathQuill's `typedText`. I've tested this with all the other key combos too--- it doesn't seem to break the selection-creating variants which is a good sign.
=> Better Navigation: Fix Ctrl+Backspace and Ctrl+Delete

src/globals/Calc.ts, src/plugins/pillbox-menus/components/PillboxMenu.tsx, src/plugins/pillbox-menus/index.ts, src/plugins/pillbox-menus/pillbox-menus.replacements
- Always use vertical pillbox in geometry (this removes a broken replacement)
- Hide "pick a tool to get started" when opening pillbox menu
=> Fix pillbox menus in /geometry

parsing/parsenode.ts, text-mode-core/TextAST/index.ts, text-mode-core/aug/AugLatex.ts, text-mode-core/aug/augLatexToRaw.ts, text-mode-core/aug/augNeedsParens.ts, text-mode-core/aug/rawToAug.ts, text-mode-core/down/astToAug.ts, text-mode-core/down/textToAST.ts, text-mode-core/down/textToAug.unit.test.ts, text-mode-core/tests/roundTripEmit.unit.test.ts, text-mode-core/tests/roundTripParse.unit.test.ts, text-mode-core/up/astToText.ts, text-mode-core/up/augToAST.ts, text-mode-core/up/needsParens.ts
Now `{x>2}` is parsed as a restriction instead of a piecewise; this allows stuff like `polygon(...)*{a>3}` to work.
This really makes me want to support implicit multiplication (omitting `*`). #756.
=> Support Restriction in Text Mode

src/plugins/video-creator/backend/export.ts, src/plugins/video-creator/components/LoadingPie.tsx
Fixes #779. Problem was not (as guessed) parsing log messages. It was namespace stuff, and I didn't even push the SVG to the page.
Problem was introduced in https://github.com/DesModder/DesModder/pull/319/commits/8c1d3c969653f5a238f9e6cfabce8eea2eebf1dc. Firefox's linter complained about the innerHTML, so I replaced it (incorrectly) with createElement stuff.
=> Fix Video Creator Loading Pie for Export

src/plugins/pillbox-menus/components/PillboxMenu.tsx
very basic pr, sure hope i didn't mess anything up
the delay between the menus opening and closing is minimal, <10ms
arises from didMountContainer getting called within a tick dispatched from toggleMenu
=> Fix PillboxMenu nested dispatch (closes #780)

package-lock.json, package.json, src/preload/replacementHelpers/cacheReplacement.ts
We'll use idb soon for Wakatime (#817), and no need to have two different IndexedDB wrappers
=> Use idb instead of idb-keyval

src/MainController.ts, src/plugins/PluginController.ts, src/plugins/better-navigation/index.ts, src/plugins/expr-action-buttons/index.ts, src/plugins/index-replacements.ts, src/plugins/index.ts, src/plugins/intellisense/index.tsx, src/plugins/manage-metadata/index.ts, src/plugins/multiline/index.ts, src/plugins/override-keystroke/index.ts, src/plugins/override-keystroke/override-keystroke.replacements, src/plugins/pillbox-menus/index.ts, src/preload/moduleReplacements.ts, src/utils/listenerHelpers.ts
Multiline, Better Navigation, and Intellisense each hook into the key handler using monkey-patching. Now they've started conflicting each other.
Instead of monkey-patching, use a replacement (regular-patching) and call a method on a new override-keystrokes plugin.
The ?w=1 flag https://github.com/DesModder/DesModder/pull/824/files?w=1 removes whitespace-only changes.
=> Fix intellisense key handling in the presence of other plugins

src/plugins/intellisense/index.tsx, src/plugins/intellisense/latex-parsing.tsx
This fixes bug where `.` doesn't get typed after a subscript when the 'auto-subscriptify' option is enabled in Intellisense.
=> Fix dot after subscriptify

src/plugins/intellisense/latex-parsing.tsx, src/plugins/intellisense/view.tsx
Fixes #705. Doesn't show useful documentation, but at least it's not saying `n` for `sin()`.
=> Handle operatornames in Intellisense

package-lock.json, package.json
We use .replacements now instead of babel.
=> Remove babel types

src/plugins/video-creator/components/MainPopup.less
The Japanese titles were wrapping for some reason.
=> Don't wrap text inside segmented control for video creator

src/plugins/video-creator/backend/capture.ts, src/plugins/video-creator/components/CaptureMethod.tsx, src/plugins/video-creator/index.ts
The problem was we were stopping the capture by throwing an error. But it was inside a callback (sometimes), so that didn't work in some situations. Now, no error throwing. Use promises without rejecting.
Fixes https://github.com/DesModder/DesModder/issues/776
=> Fix cancelling slow captures (slider and ticks)

src/panic/panic.html
I presume this change was made a while ago when the panic button was on top of Desmos' home link. I was checking the git history of this line, and it seems the last change was about a year ago in May, so I think it lines up. Either way the purpose of this change is because currently the link is unclickable until the popover is open, but then it is blocked, so it renders the home link unusable.
=> Remove home link disable on panic popover

src/plugins/video-creator/index.ts, src/plugins/video-creator/orientation.ts
This fixes bug where you can't scroll while a graph is spinning.
Really, the listeners should only be attached when the view is mounted, but I struggled getting that to work.
=> Don't update video creator latex when menu closed

src/plugins/hide-errors/hide-errors.replacements
This happens for error triangles other than the main statement, such as for clickable objects with undefined variables.
=> Handle exprId not passed in

src/components/Button.less, src/components/SegmentedControl.less, src/plugins/custom-mathquill-config/custom-mathquill-config.less, src/plugins/find-replace/ReplaceBar.less, src/plugins/hide-errors/hide-errors.less, src/plugins/pillbox-menus/components/PillboxMenu.less, src/plugins/pin-expressions/pinExpressions.less, src/plugins/set-primary-color/_overrides.less, src/plugins/set-primary-color/clean-css.mjs, src/plugins/set-primary-color/custom-overrides.less, src/plugins/set-primary-color/index.ts, src/plugins/show-tips/Tip.less, src/plugins/show-tips/index.ts
Desmos changed `.dcg-calculator-api-container` to `dcg-calculator-api-container-v1_10`. PR changes to using either `.dcg-container` (for most stuff) or `.dcg-sliding-interior` (for set-primary-color, which also has to affect the header).
=> Fix container selector

localization/en.ftl, src/plugins/video-creator/backend/capture.ts, src/plugins/video-creator/components/CaptureMethod.css, src/plugins/video-creator/components/CaptureMethod.tsx, src/plugins/video-creator/index.ts
It just calls `.screenshot()` instead of `.asyncScreenshot`. Made possible by the `notifyWhenSynced` function.
I don't know why I yapped so much at #184. Fixes #184.
=> Add "fast screenshots" option for 2d video creator

docs/CHANGELOG.md, package-lock.json, package.json, public/chrome/manifest.json, public/firefox/manifest.json, src/plugins/set-primary-color/_overrides.less, src/plugins/set-primary-color/clean-css.mjs
@SlimRunner I added some extra instructions in clean-css.mjs here with regards to generating the css overrides. Downloading the css isn't yet automated in the same way that `setup-unit.js` automatically downloads the JS.
=> Prepare v0.13.10

src/globals/Calc.ts, src/plugins/intellisense/index.tsx
This patch fixes the Intellisense lookup which currently fails to sort the items by drawing order because Desmos removed a property from Calc.
The property removed was the `Calc.controller.listModel.drawOrder`. It's changed to `Calc.controller.listModel.drawLayers[...].drawOrder`. I am not sure why `drawLayers` is an array instead of an object, but I opened several graphs and they all had only one element. Maybe it's future proofing for later, but whatever the case I hardcoded the zero in the intellisense plugin.
=> Fix draw order lookup in Intellisense

src/components/desmosComponents.ts, src/core-plugins/override-keystroke/override-keystroke.replacements, src/plugins/hide-errors/hide-errors.replacements, src/plugins/text-mode/text-mode.replacements
It seems like an oddly simple fix, but I am not 100% confident that was it (on the off change that I searched the wrong new replacement). The error was correctly identified by the panic system.
> "Show style circles and expression footers for Text Mode statements"
The page crashes if you try to open text mode when there is an expression with a style circle present.
=> Fix broken replacements

localization/ja.ftl
Because the original ja.ftl file contained some unnatural expressions that were machine-translated and lacked some localization, I have made overall improvements, including correction of mistranslations and unification of inconsistent notations.
=> Improve Japanese localization

src/plugins/video-creator/backend/capture.ts, src/plugins/video-creator/components/CaptureMethod.tsx, src/plugins/video-creator/index.ts
This PR fixes #920 with some caveats (see below)
Changes made
- screenshot mode set to "contain"
- pixel ratio is clamped to 1
- stop preview play when "delete all" is clicked
I believe there is no point in allowing pixel ratios that are less than 1 now that Desmos doesn't seem to support them anymore. As pointed out in the issue linked, this causes some screenshots below native resolution to actually increase in resolution. The drawback—which I think is reasonable—is that now these screenshots are no longer matched with what you see on screen (as if the same pixel ratio was checked on) as opposed to the default behavior.
The "contain" option fixes alignment problems with screenshots taken without fast screenshots. For some reason, these were preserving x instead which is odd because the …
=> Fix wrong screenshot scaling

src/plugins/compact-view/compact.less
This is a quality of life change.
The default font size for expressions is 110% above the regular font size. That means that evaluation containers have a font size of 16 px while expressions have a font size of roughly 17.6 px. Default math font size now reflects the actual default (16 px).
Now when the spacing slider is all the way to the left, Desmos has a _default feel_. Previously you had to choose between the expressions or evaluation containers having a larger font-size than they normally do. This change was made to remove visual snags if all you want to enable is the "hide folder toggle" or "no separating lines" but keep the scaling off.
=> Fix compact-view default font ratio

src/panic/panic.ts
This fixes #933
As noted in the issue above, force-disabled plugins which came in "groups" (related by dependencies) would essentially be able to be disabled an infinite number of times. The culprit was that the dependencies were not filtered by the list of force-disabled plugins.
I tested tested this by purposefully breaking random replacements with multiple dependencies. It seemed to work fine in all my tests. However, I am not sure yet if there is a cleaner way to achieve the same (without using `window` or `as any`), but it is currently just four lines.
=> Prevent panic plugins showing twice in Menu

src/globals/Calc.ts, src/utils/depUtils.ts
The function `getCurrentGraphTitle` broke because a property changed in the `calc` object. This PR fixes the issue.
It is a very minor issue, but I thought of making it a PR before I forget.
Funny enough, I [fixed this same issue in my old user-script](https://github.com/SlimRunner/desmos-scripts-addons/commit/5a9fe674d85ee6abff42aabf5fcdcc83e1237e14) about a month ago, and even though I got that snippet from fireflame, I did not connect the dots until today that it was likely broken here too.
=> Fix broken call to get graph title

package-lock.json, package.json, src/plugins/code-golf/index.tsx, text-mode-core/down/textToAST.ts, text-mode-core/tsconfig.json, text-mode-core/up/augToAST.ts, tsconfig-base.json
This PR bumps these packages to the latest version:
* typescript v5.4.3 -> v5.7.2
* typescript-eslint v8.15.0 -> v8.16.0
Includes the following changes:
* Remove no longer needed type assertions
Path-sensitive type inferences has been added for `Array.prototype.every` and `Array.prototype.filter` ([typescript@5.5](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#inferred-type-predicates))
* Add non-null assertion to `cachedGolfStatsPool.keys().next().value` 
`BuiltinIteratorReturn` is now changed from `any` to `undefined` in projects with `strict: true` ([typescript@5.6](https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#strict-builtin-iterator-checks-(and---strictbuiltiniteratorreturn)))
* Enable `allowImportingTsExtensions` and `emitDeclarationOnly` …
=> Deps: Bump typescript to v5.7

src/plugins/paste-image/index.ts
When adding checks by `areImagesEnabled()` and `isUploadingImages()`, I forgot to exclude cases where `clipboardFiles.length === 0`, i.e. when plain text is pasted. For example, if we paste plain text in 3D calculator where images are not enabled, we get a `paste-image-error-images-not-enabled` warning.
This PR fixes the flow to first exclude such cases (return early).
=> Paste Image: Fix inappropriate warnings when pasting plain text

metadata/manage.ts, metadata/migrate.ts, src/MainController.ts, src/core-plugins/manage-metadata/index.ts, src/core-plugins/manage-metadata/manage-metadata.replacements, src/core-plugins/manage-metadata/sync.ts, src/globals/Calc.ts, src/globals/models.ts, src/plugins/GLesmos/index.ts, src/plugins/index.ts, src/plugins/intellisense/state.tsx, src/tests/puppeteer-utils.ts
Fixes https://github.com/DesModder/DesModder/issues/310:
1. When pasting a graph by link (with DesModder installed), merge the metadatas together.
2. Create a single secret note for dsm-metadata, instead of a regular note contained inside a secret folder.
A side-change to clean up junk notes with DesModder not installed:
3. Delete notes (and containing folders) that look like dsm-metadata but without the ID. These can be created when pasting a graph by link when DesModder is not installed. The IDs don't line up, so there is no point keeping them around.
=> Manage metadata: merge when loaded from link, don't create folder, delete duplicates

src/globals/Calc.ts, src/plugins/text-mode/index.ts
Closes #958
The event listener will be removed when unmounting the editor for compatibility. Usually GC works so I'm not sure if it is always necessary.
=> Add a scroll event listener to `view.scrollDOM` that closes the item settings menu

src/plugins/code-golf/GolfStatsPanel.tsx, src/plugins/code-golf/golf-model.ts, src/plugins/code-golf/index.ts
1. Avoid issue where dragging the sole child of a folder would hide the folder stats, changing the folder's height.
2. Always compute golf stats for pinned expressions, instead of hiding once the true expression scrolls out of view.
=> Fixes to when golf stats are hidden.

src/plugins/intellisense/intellisense.int.test.ts, src/plugins/intellisense/latex-parsing.tsx
Fixes #955. The problem was that intellisense scans backwards including numbers, so `ab2cd` can auto-subscriptify to `a_{b2cd}`. However, it trims leading digits, so `3ab2cd` doesn't try auto-subscriptifying to `3_{ab2cd}`; it goes to `a_{b2cd}` instead. But the calculation for how many times to press "backspace" wasn't reduced when trimming the leading digits.
=> Reduce goBack count when trimming leading numbers

src/components/desmosComponents.ts, src/plugins/code-golf/golf-model.ts, src/plugins/video-creator/components/CaptureMethod.tsx, src/plugins/video-creator/components/ManagedNumberInput.tsx
This fixes error logged to console when the magic button (auto-detect dimensions) is pressed when capture width or height is empty. Desmos uses `getPlaceholder().trim()` instead of `getPlaceholder()?.trim()`.
=> Force string placeholder

localization/en.ftl, src/core-plugins/manage-metadata/index.ts, src/globals/Calc.ts
When you load a GLesmos-enabled graph but you don't have GLesmos enabled, we show a warning. The current behavior is quite bugged.
1. Localize the message (cuz why not)
2. If GLesmos is enabled on the first load of the page, we previously still showed a warning because it wasn't loaded at the time of the event that triggers the message. This fixes that by checking if GLesmos will be enabled.
3. When navigating between graphs in the shell menu, the toast was previously replaced by a toast like "Opened 'Untitled Graph'". Now, we replace that with the GLesmos message.
=> Localize and fix Glesmos warning

public/chrome/net_request_rules.json, src/background.ts, src/plugins/set-primary-color/clean-css.mjs, src/plugins/video-creator/video-creator.int.test.ts, src/preload/script.ts, src/tests/puppeteer-utils.ts, src/tests/setup-unit.js
Desmos switched JS urls from `calculator_3d-*.js`, `calculator_desktop-*.js`, and `calculator_geometry-*.js` to a single `shared_calculator_desktop-*.js`. Fix blocking and preload to work with the new URL.
I'm keeping in the old URLs in case they change back. They can in theory be removed in the future.
Fixes #970
=> Fix preload to work with shared_calculator_desktop

src/plugins/better-evaluation-view/better-evaluation-view.int.test.ts, src/plugins/better-evaluation-view/better-evaluation-view.replacements, src/plugins/better-evaluation-view/components/ColorEvaluation.tsx, src/plugins/better-evaluation-view/components/ListEvaluation.tsx
- `this.props.val()` is not working anymore, so I replaced them with `this.getEvaluationRHS().val` or `itemModel.formula.typed_constant_value.value`. For lists, the latter is not affected by truncation and always return all the elements.
- Added a replacement for `emptyList`
- Wrapped `StaticMathQuillView` with `div.dcg-evaluation-view__wrapped-value` to apply evaluation view styles
=> Fix broken replacements for Better Evaluation View

src/plugins/text-mode/components/TextModeToggle.tsx, src/plugins/text-mode/index.ts, src/plugins/text-mode/text-mode.int.test.ts
Fix #964.
Just set `isHiddenFromUI = true` on all item models when in text mode, using the established `afterUpdateTheComputedWorld` hook.
=> Fix offset menu in text mode

src/plugins/find-replace/backend.ts, src/plugins/find-replace/find-replace.unit.test.ts
We were adding numbers to `-1` which just indicates not-found.
Fixes find-replace involving derivatives `\frac{d}{dt}`
=> Don't replace derivative when not found

src/core-plugins/override-keystroke/override-keystroke.replacements
Just added one line to fix replacement error for override-keystroke.
=> Fix broken replacements for override-keystroke

.github/workflows/lint-and-test.yml, docs/DEVELOPMENT.md
Set `node-version` to 22.x in workflows/lint-and-test.yml and updated DEVELOPMENT.md accordingly. (Node.js v18 is going to be EOL at the end of April.)
This PR also allows several ECMAScript features (~~like import attributes~~This was my misunderstanding. It is backported to v18) to be available.
=> Use Node.js v22 in GitHub Actions and update DEVELOPMENT.md

src/DCGView.ts, src/components/desmosComponents.ts, src/core-plugins/expr-action-buttons/expr-action-buttons.replacements, src/core-plugins/pillbox-menus/index.ts, src/core-plugins/pillbox-menus/pillbox-menus.replacements, src/plugins/GLesmos/glesmos.replacements, src/plugins/better-evaluation-view/better-evaluation-view.replacements, src/plugins/code-golf/code-golf.replacements, src/plugins/hide-errors/hide-errors.replacements, src/plugins/show-tips/index.ts, src/plugins/show-tips/show-tips.replacements, src/plugins/text-mode/text-mode.replacements, src/preload/moduleOverrides/insert-panels.replacements, src/preload/replaceElement.ts
Gracefully handle the following changes:
- `$DCGView.createElement` becomes a single minified ident `$createElement`.
- `children` is passed as a prop to `createElement` instead of a third parameter.
- `$DCGView.const()` removed (heading towards no getters).
After Desmos updates to use these changes, the Alternatives in the replacement files can be removed, as well as some code marked as `TODO-remove-children-props`.
=> Fix future replacement errors

src/plugins/right-click-tray/right-click-tray.replacements
Replaced `$DCGView.addCustomAttribute` with a single identifier `$addCustomAttribute`
=> Fix broken replacements for Right Click Tray

localization/en.ftl, localization/es.ftl, src/plugins/better-navigation/index.less, src/plugins/better-navigation/index.ts
Add setting to show or hide scrollbar for long expressions when better navigation is enabled.
As [discussed here](https://discord.com/channels/1095245998747557978/1095245999473176709/1356759569283551404), it may be convenient to hide it in devices with trackpads and/or touch screen.
=> Better-nav-hide-scroll-bar

.github/workflows/build.yml, .github/workflows/lint-and-test.yml
This should fix the CI failure in #1016
=> Bump actions/checkout and actions/setup-node to the latest version

.github/workflows/build.yml, .github/workflows/lint-and-test.yml, src/globals/Calc.ts, src/globals/index.ts, src/globals/models.ts, src/plugins/better-evaluation-view/better-evaluation-view.int.test.ts, src/plugins/better-evaluation-view/better-evaluation-view.replacements, src/plugins/better-evaluation-view/components/ListEvaluation.tsx, src/plugins/better-evaluation-view/index.ts, src/tests/puppeteer-utils.ts, src/utils/depUtils.ts
Fix #1015
- Extracted `NonfolderItemModelBase["formula"]` types to interface
- Made property `expression_type` and `is_inequality` present only in `ExpressionFormula`
- Made property `is_inequality` optional since it exists only in inequalities as far as I could find
- Added typings for `typed_constant_value`
- Return `itemModel.formula.typed_constant_value` instead of `itemModel.formula.typed_constant_value.value` in `listEvaluation` callbacks so that we can access to the `valueType` property
- Added tests for `EmptyList`, `ListOfComplex`, `ListOfPoint`, and `ListOfPoint3D`
- Made `expectEval` and `expectEvalPlain` into methods of `Driver` to deal with multiple expressions in one test case
to-do:
- Add more detailed typings for `Private`
=> Fix issue with list of points in Better Evaluation View

src/core-plugins/pillbox-menus/components/PillboxMenu.tsx, src/plugins/video-creator/backend/export.ts, src/plugins/video-creator/components/MainPopup.tsx
With webp selected, ffmpeg will now be run with `-vcodec libwebp -lossless 1 -loop 0` and generate an animated WebP file.
Tweaked PillboxMenu styles to prevent the "Select export type" control from overflowing.
=> Add support for exporting frames as WebP

.vscode/extensions.json, .vscode/settings.json, docs/DEVELOPMENT.md
- Set the default formatter to Prettier in the workspace settings
- Suggest installing Prettier if it isn't installed already
- Update the docs to match
=> Automatically suggest using the Prettier extension for VSCode

src/core-plugins/pillbox-menus/components/PillboxButton.tsx, src/core-plugins/pillbox-menus/components/PillboxContainer.less, src/core-plugins/pillbox-menus/components/PillboxContainer.tsx, src/core-plugins/pillbox-menus/components/PillboxMenu.less, src/core-plugins/pillbox-menus/components/PillboxMenu.tsx, src/core-plugins/pillbox-menus/index.ts, src/core-plugins/pillbox-menus/pillbox-menus.replacements, src/plugins/performance-info/performance-info.int.test.ts, src/plugins/text-mode/text-mode.replacements, src/plugins/video-creator/video-creator.int.test.ts
This gets the correct height when dragging the expressions list vertically to cover them.
=> Create pillbox buttons in the same way as desmos

localization/en.ftl, src/plugins/better-evaluation-view/better-evaluation-view.int.test.ts, src/plugins/better-evaluation-view/better-evaluation-view.replacements, src/plugins/better-evaluation-view/components/ListEvaluation.tsx, src/plugins/better-evaluation-view/config.ts, src/tests/puppeteer-utils.ts
Adds a new option "Advanced floating point" (default false) to show NaN/∞/-∞ instead of undefined, and '-0' for negative 0.
Fixes #1020
Also fixes the bug where NaN/∞/-∞ was shown even if BEV was disabled.
Also disables "Show list elements" by default since Desmos has its builtin list display.
=> Add 'floats' config to better-evaluation-view

apply-replacements/applyReplacement.ts, apply-replacements/replacements.md, apply-replacements/tokenize.ts, src/core-plugins/pillbox-menus/pillbox-menus.replacements, src/plugins/GLesmos/glesmos.replacements, src/plugins/code-golf/code-golf.replacements, src/plugins/hide-errors/hide-errors.replacements, src/plugins/show-tips/show-tips.replacements, src/plugins/text-mode/text-mode.replacements
Use two dollar signs like `$$const` to do a match that handles either an identifier like `const` or chained member accesses like `p.const` or `a.b.c.d.e.f`.
Short term purpose is to match both `DCGView.const("abc")` and `const("abc")`, but long-term it provides an easy way to handle any future such minifications that Desmos does.
=> Support Dot replacements

src/DCGView.ts, src/components/desmosComponents.ts, src/core-plugins/expr-action-buttons/components/ActionButtons.tsx, src/core-plugins/pillbox-menus/components/Menu.tsx, src/core-plugins/pillbox-menus/components/PillboxContainer.tsx, src/plugins/intellisense/view.tsx, src/plugins/pin-expressions/components/PinnedPanel.tsx, src/utils/utilComponents.tsx
Use `For.Keyed` instead of `For`. The main difference here is that the parameter is a getter instead of the list entry itself. Desmos will be migrating to this being the only way to use `For` and removing `For.Keyed`, so fallback to `For` if `For.Keyed` is not available.
Not the prettiest migrations.
=> Use Keyed for

apply-replacements/applyReplacement.ts, apply-replacements/replacements.md, apply-replacements/tokenize.ts, src/core-plugins/pillbox-menus/pillbox-menus.replacements, src/plugins/GLesmos/glesmos.replacements, src/plugins/code-golf/code-golf.replacements, src/tests/smoke.int.test.ts
1. Change hook for GLesmos replacements (it's currently broken, this will fix)
2. Include panic messages in assertion errors, so the integration tests will actually say what match failed.
3. Add and use a non-greedy match that makes skipping over classes easier. It's not robust against rearranging the classes, but this is a decent improvement.
=> Robustify replacements

localization/en.ftl, package-lock.json, src/core-plugins/pillbox-menus/components/Menu.tsx, src/globals/Calc.ts, src/plugins/index-replacements.ts, src/plugins/index.ts, src/plugins/quake-pro/config.ts, src/plugins/quake-pro/index.ts, src/plugins/quake-pro/quake-pro.replacements, src/preload/moduleReplacements.ts
This feature introduces an ability to increase the Field of View of the 3D calculator beyond the regular limit.
The name comes from FOV setting in Minecraft, where if you maximize the viewport, its named as "Quake Pro". Can rename it to anything you like, i found this catchy.
The method is to multiply anything related to `perspectiveDistortion` when it comes to rendering. This will retain vanilla behavior, albeit with a higher magnification limit.
(Thanks to @SlimRunner for teaching me how to do replacements!!!)
=> Added "Quake Pro" Feature

localization/ja.ftl
- Added Japanese translations for Quake Pro and BEV floats.
- Renamed '改行つき数式' (Multiline) to '複数行モード', which is more concise & less clunky.
=> Update Japanese localizations

src/plugins/hide-errors/hide-errors.replacements, src/plugins/multiline/index.ts
- Only suppress errors on shift-enter if there is an error
- Ensure shift-enter multiline has priority over shift-enter hide-error (Shouldn't change anything, just is careful)
Fixes most problems associated with #515, so I'd be okay saying #515 is fixed. The proposal in that issue (of removing errorHidden) comes at the risk of not suppressing alternating errors, so might as well not risk that.
=> Only suppress errors on shift-enter if there is an error

src/globals/Calc.ts, src/plugins/video-creator/backend/capture.ts, src/plugins/video-creator/components/PreviewCarousel.less, src/plugins/video-creator/index.ts
Fixes #533 by changing the captures. There is no extra checkbox added. Just uses the graph settings from the wrench menu.
This changes the captures, so it applies to zip export as well as the video exports.
=> Respect reverse contrast in video creator capture
