DesModder/DesModder

- public/manifest.json
- src/Controller.ts
- src/content.ts
- src/desmodder.ts
- src/messages.ts
- src/utils.tsx
> ✨ 73 Persist settings in extension storage

- src/plugins/video-creator/View.ts
Resolves Can't see capture region frame on a black background #125
> 💄 Add a white box shadow on the capture frame

- config/webpack.config.base.js
- public/manifest.json
- src/background.ts
> ✨ Click on extension icon to open Desmos

- src/desmodder.ts
- src/globals/Calc.ts
- src/plugins/duplicate-hotkey/duplicateExpression.ts
- src/plugins/duplicate-hotkey/index.ts
> ✨ [duplicate-hotkey] Duplicate non-expressions

- src/plugins/wolfram2desmos/config.ts
- src/plugins/wolfram2desmos/index.ts
- src/plugins/wolfram2desmos/wolfram2desmos.js
@Heavenira recently made a refactor in their wolfram2desmos script. I ported the new code to integrate with Desmodder. This refactor was discussed in #142.
> 🔨 Integrated wolfram2desmos refactor

- src/plugins/pin-expressions/moduleOverrides.ts
> Prevent arrow keys from moving between pinned and unpinned expressions

- src/plugins/wolfram2desmos/wolfram2desmos.ts
More scenarios which will prevent wolfram2desmos from parsing
> Disallowed {} brackets + Disallowed // for URL instance

- src/main/Controller.ts
- src/plugins/pin-expressions/pinExpressions.less
> 167 tweak box shadow

- README.md
- src/plugins/duplicate-hotkey/index.ts
- src/plugins/pin-expressions/moduleOverrides.ts
- src/preload/withinFunctionAssignment.ts
> Show button for duplication of non-expressions

- src/plugins/video-creator/backend/capture.ts
This fixes two related issues
- Simulations didn't turn the capture button to a cancel button
- Simulations would occassionaly stop after a few frames
> Fix simulation capture

- src/parsing/parsenode.ts
- src/plugins/GLesmos/computeContext.ts
- src/plugins/GLesmos/depOrder.ts
- src/plugins/GLesmos/exportAsGLesmos.ts
Tested with https://www.desmos.com/calculator/5st28xna0v
> Handle GLesmos dependency orders

- src/plugins/GLesmos/exportAsGLesmos.ts
- src/plugins/GLesmos/glesmosCanvas.ts
- canvas size is (for now) based on window size
- added support for points (fixed bug where they'd be defined as floats instead of vec2s)
- canvas now scrolls with regular desmos graph
> vec2 support, canvas resize + adjusts w/ graphpaperbounds

- src/plugins/wolfram2desmos/wolfram2desmos.ts
This should clear up some issues when pasting piecewise expressions. Not tested formally yet.
> Piecewise statements implemented.

- src/main/Controller.ts
> Refresh GLesmos expressions when toggling the plugin

- src/plugins/video-creator/Controller.ts
- src/plugins/video-creator/backend/export.ts
- src/plugins/video-creator/components/MainPopup.less
- src/plugins/video-creator/components/MainPopup.tsx
> Allow naming output file

- src/globals/Calc.ts
- src/main/Controller.ts
- src/plugins/folder-tools/index.ts
Also calls updateTheComputedWorld to apply the changes before exiting ELM.
> Fix undo-redo state stack for folder-tools actions

- .github/workflows/test.yml
- .prettierignore
- package-lock.json
- package.json
- src/plugins/wolfram2desmos/wolfram2desmos.ts
Checks formatting and typescript correctness
> Add CI workflow

- src/plugins/wolfram2desmos/wolfram2desmos.ts
As you can see, my RegEx can be very shabby at times :D
(Courtesy of @donno2048 from https://github.com/Heavenira/wolfram2desmos/issues/21)
> `|` in RegEx was wrong

- src/plugins/video-creator/backend/export.ts
Fix for #333 
I created a quick object to map data types to media types. Let me know if you prefer an interface instead.
> Fix hardcoded Blob datatype

- src/globals/Calc.ts
- src/plugins/video-creator/Controller.ts
- src/plugins/video-creator/components/MainPopup.tsx
> Default video export name to graph title

- src/plugins/video-creator/Controller.ts
- src/plugins/video-creator/backend/export.ts
- src/plugins/video-creator/components/MainPopup.tsx
It now changes to the new graph title if you switch graphs
> Improve default video name

- src/plugins/video-creator/backend/export.ts
> Fix mp4 export (yuv420p instead of yuv444p)

- src/globals/Calc.ts
- src/plugins/duplicate-hotkey/index.ts
> Fix duplicate hotkey for folders

- src/main/Controller.ts
- src/plugins/GLesmos/index.ts
> Disable GLesmos on page load, always

- public/chrome/net_request_rules.json
- src/background.ts
> Fix graph recovery thumbnails

- src/components/Menu.less
- src/components/Menu.tsx
- src/main/Controller.ts
- src/plugins/GLesmos/colorParsing.ts
- src/plugins/builtin-settings/config.ts
- src/plugins/index.ts
- src/plugins/set-primary-color/index.ts
- Update favicon color
- Allow not updating favicon color
- Change cursor to pointer on color picker
- Change color continuously on input
- Add reset button to all settings
> Improve set-primary-color plugin

- .gitignore
- README.md
- docs/CHANGELOG.md
- docs/RELEASE.md
- docs/reviewer-notes-ff.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- Bump version to 0.7.2
- Update Readme and Changelog
- Improve process documentation
> Improve process documentation

- src/plugins/video-creator/backend/export.ts
> Fix 0-byte export of mp4 on ubuntu and some mac

- jest.config.js
Makes test:jest much faster, from around 12 seconds to 2
> Enable isolatedModules in ts-jest

- src/plugins/set-primary-color/index.ts
- src/plugins/set-primary-color/overrides.less
- Fix favicon after disabling set-primary-color plugin
- Update color overrides by script
- Fix favicon color override when overriden
> Fix set-primary-color plugin

- src/plugins/GLesmos/Controller.ts
- src/plugins/GLesmos/builtins.ts
- src/plugins/GLesmos/emitChunkGL.ts
- Prefix all GLesmos builtins to avoid collisioins (resolves #372)
- Implement median (resolves #369)
- Fix GLesmos error reporting on the main page
> GLesmos fixes

- docs/CHANGELOG.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- src/plugins/text-mode/docs/intro.md
- Bump version to 0.8.0
- Update changelog
> 🚀 Prepare 0.8.0

- src/plugins/show-tips/tips.ts
Added some audio trace and other tips.
> Added some tips

- localization/en.ftl
- src/plugins/performance-info/index.ts
> 🌐 : Fix performance-info translations

- docs/CHANGELOG.md
- docs/reviewer-notes-ff.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- Bump version number
- Update changelog
- Update reviewer notes
> Prepare 0.8.1

- docs/CHANGELOG.md
- docs/reviewer-notes-ff.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- src/components/InlineMathInputView.tsx
- Fix inline math inputs fr fr
- Prepare 0.8.2
> Prepare 0.8.2

- src/plugins/text-mode/aug/augToRaw.ts
- src/plugins/text-mode/down/cstToAST.ts
- src/plugins/text-mode/down/textToAug.test.ts
- src/plugins/text-mode/up/getText.ts
> Text mode fixes

- src/plugins/GLesmos/exportAsGLesmos.ts
> Clamp fill opacity to between 0 and 1

- src/components/SegmentedControl.tsx
- src/components/desmosComponents.ts
- src/globals/Calc.ts
- src/globals/window.ts
- src/main/Controller.ts
- src/plugins/video-creator/Controller.ts
- src/plugins/video-creator/components/CaptureMethod.tsx
- src/plugins/video-creator/components/MainPopup.tsx
- src/preload/moduleOverrides.ts
- src/preload/moduleOverrides/main__calc_desktop.ts
> Fix SegmentedControls and graph title detection

- src/plugins/show-tips/Tip.less
> Widen tips when the expressions list is wide

- src/components/SegmentedControl.less
- src/components/SegmentedControl.tsx
This was a regression from #440
> Fix disabled segmented control button

- src/parsing/IR.ts
- src/plugins/GLesmos/builtins.ts
- src/plugins/GLesmos/emitChunkGL.ts
- src/plugins/GLesmos/outputHelpers.ts
- Move native function dependencies to helper function
- Fix arrays in ternaries for glesmos
- Export each branch of IRInstruction tagged union
> Fix ternary expressions involving lists in GLesmos

- src/plugins/video-creator/backend/export.ts
Remove pix_fmt, which has been causing issues. yuv444 is better than 0 bytes of yuv420
> Fix mp4 export

- docs/CHANGELOG.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- Bump version to 0.8.4
- Update changelog
> Prepare 0.8.4

- public/firefox/manifest.json
- src/background.ts
- src/plugins/index.ts
- src/plugins/wakatime/heartbeat.ts
- src/plugins/wakatime/index.ts
- src/preload/content.ts
- src/utils/messages.ts
- Fix Firefox wakatime
- Restrict page from accessing secret key
- Log wakatime fetch errors
> Fix Firefox WakaTime

- docs/CHANGELOG.md
- docs/reviewer-notes-ff.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- Prepare 0.8.5
- Update reviewer notes
> Prepare 0.8.5

- src/plugins/wakatime/heartbeat.ts
Yes I am going to be a stickler about this :D
> plural'd "Desmos Project"

- src/components/Menu.tsx
- src/main/Controller.ts
- src/plugins/GLesmos/index.ts
- src/plugins/builtin-settings/index.ts
- src/plugins/debug-mode/index.ts
- src/plugins/duplicate-hotkey/index.ts
- src/plugins/find-replace/index.ts
- src/plugins/folder-tools/index.ts
- src/plugins/hide-errors/index.ts
- src/plugins/index.ts
- src/plugins/performance-info/index.ts
- src/plugins/pin-expressions/index.ts
- src/plugins/right-click-tray/index.ts
- src/plugins/set-primary-color/index.ts
- src/plugins/shift-enter-newline/index.ts
- src/plugins/show-tips/index.ts
- src/plugins/text-mode/index.ts
- src/plugins/video-creator/index.ts
- src/plugins/wakatime/index.ts
- src/plugins/wolfram2desmos/index.ts
- src/preload/content.ts
- src/utils/messages.ts
- Refactor menu component
- Rewrite controller to use general Plugin type, not consts
- Prefer Plugin type rather than casting `as const`
- Fix plugin settings
> Refactor plugins

- docs/CHANGELOG.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- Bump version to 0.8.6
- Update changelog
> Prepare v0.8.6

- src/preload/moduleOverrides/main__calc_desktop.ts
- src/preload/workerOverrides/features__graph.ts
- Fix topLevelComponents patch
- Fix GLesmos
> Fix bugs from the latest update

- package-lock.json
- package.json
- src/preload/replacementHelpers/cacheReplacement.ts
- src/preload/script.ts
Cache replacements, getting Largest Contentful Paint from ~3s to ~1.2s
> Cache replacements for loading speed

- src/plugins/GLesmos/emitChunkGL.ts
- src/plugins/GLesmos/exportAsGLesmos.ts
> Fix GLesmos derivatives of summations

- src/plugins/GLesmos/ViewportTransforms.ts
- src/plugins/GLesmos/glesmosCanvas.ts
Log plots aren't implemented, but this fixes the current transforms being NaN.
Should probably be merged ASAP to restore functionality.
> hotfix transforms problem

- localization/en.ftl
- src/plugins/better-evaluation-view/ColorSwatch.less
- src/plugins/better-evaluation-view/config.ts
- src/plugins/better-evaluation-view/index.ts
- src/plugins/index.ts
- src/preload/moduleOverrides/better-evaluation-view.replacements
- src/preload/moduleReplacements.ts
Better Evaluation View but I'm actually kinda motivated this time
> Better Evaluation View (Attempt 2)

- src/preload/moduleOverrides/better-evaluation-view.replacements
Just a small override to truncatedLatexLabel
> Fix undefined in lists

- src/main/Controller.ts
- src/plugins/debug-mode/index.ts
- src/plugins/folder-tools/index.ts
- src/plugins/hide-errors/index.ts
- src/plugins/index.ts
- src/plugins/shift-enter-newline/index.ts
- src/preload/moduleOverrides/shift-enter-newline.replacements
Just slightly more work: need to check if they're enabled in some spots
> Remove alwaysEnabled plugins

- src/plugins/GLesmos/emitChunkGL.ts
- src/plugins/GLesmos/outputHelpers.ts
- src/plugins/GLesmos/workerDeps.ts
- src/preload/replacementHelpers/cacheReplacement.ts
- Fix variable list access in GLesmos
- Fix list constants in GLesmos
> Fix GLesmos lists

- src/panic/panic.html
- src/preload/moduleOverrides/glesmos.replacements
- src/preload/replacementHelpers/applyReplacement.ts
- Remove block comments from error messages
- Fix GLesmos replacement
> Fix loading error with GLesmos

- localization/en.ftl
- src/components/Menu.less
- src/components/Menu.tsx
- src/components/PillboxContainer.tsx
- src/main/Controller.ts
- src/plugins/index.ts
- src/plugins/performance-info/PerformanceView.less
- src/plugins/performance-info/PerformanceView.tsx
- src/plugins/video-creator/components/CaptureMethod.tsx
- src/plugins/video-creator/components/MainPopup.less
- src/plugins/video-creator/components/MainPopup.tsx
- Divide plugins into categories (Fixes #405)
- Fix video-creator horizontal scrollbar
- Use popover title (primary color) in menus
> Popover menu changes

- src/components/Menu.tsx
- src/main/Controller.ts
This fixes #544 . I searched for the line, literally stared at my screen and the inspector for a minute, and then moved two lines, before realizing i moved them to far, and then moved it to where it is now. Needless to say, it works, and I have no idea about code quaility (well just blindly moving two lines), but seems to work fine!
That being said, if I revisit this, and being extremely nitpicky of myself, should the checkbox be at the same height as the first line? If you think so, I can go back and fix it again.
> Fix overflow in DesModder menu #544

- .eslintrc.js
- package.json
- scripts/audit-langs.ts
- src/globals/window.ts
- src/i18n/i18n-core.ts
- src/main/metadata/manage.ts
- src/panic/panic.ts
- src/plugins/GLesmos/shaders.ts
- src/plugins/find-replace/index.ts
- src/plugins/set-primary-color/clean-css.js
- src/plugins/set-primary-color/index.ts
- src/plugins/text-mode/down/textToRaw.ts
- src/plugins/text-mode/up/augToText.test.ts
- src/plugins/wakatime/index.ts
- src/preload/moduleReplacements.ts
- src/preload/replacementHelpers/applyReplacement.ts
- tsconfig.json
> Require no-console in eslint

- .gitignore
- .vscode/settings.json
- localization/zh-CN.ftl
- src/i18n/i18n-core.ts
zh-CN translations; .gitignore file added .vscode directory
> zh-CN translations

- src/preload/moduleOverrides/better-evaluation-view.replacements
- src/preload/replacementHelpers/applyReplacement.ts
- src/preload/replacementHelpers/cacheReplacement.ts
Draft PR, extension currently works? (except for BEV) but goes crazy panic mode
> Fix replacements

- src/components/desmosComponents.ts
- src/globals/Calc.ts
- src/globals/window.ts
- src/plugins/text-mode/LanguageServer.ts
- src/plugins/text-mode/down/style/Hydrated.ts
- src/plugins/text-mode/index.ts
- src/plugins/text-mode/lezer/completions.ts
- src/plugins/text-mode/modify.ts
- src/plugins/text-mode/tests/roundTripParse.test.ts
- src/plugins/text-mode/up/astToText.ts
- src/plugins/text-mode/up/augToText.ts
- src/plugins/text-mode/view/editor.ts
- src/plugins/text-mode/view/plugins/StyleCircle.less
- src/plugins/text-mode/view/plugins/StyleCircle.tsx
- src/plugins/text-mode/view/plugins/collapseStylesAtStart.ts
- src/plugins/text-mode/view/plugins/stmtNumbers.ts
- src/plugins/text-mode/view/plugins/styleCircles.ts
- src/plugins/text-mode/view/statementIntersection.test.ts
- src/plugins/text-mode/view/statementIntersection.ts
- src/preload/moduleOverrides/text-mode.replacements
- Show style circles in Text Mode
- Update expressions on changes from style circle menu
- Show style circle for images
- Suggest undo on converting image to draggable
- Add style circle spacer
- Update style circles on Desmos updateView
- Un-white style circles in text mode
- Collapse style mappings at start
> Show Style Circles in Text Mode

- src/plugins/intellisense/index.tsx
> Disable Intellisense by Default

- localization/es.ftl
I think it is good right now, but I want to review it another time tomorrow (well today lol) in case there is something I'm not seeing that automatic proofing may not have caught. Also, I will ask in Discord if a second pair of eyes can give it a look as well.
I'll comment with a thumbs up once that's done so you know when to merge.
> Update spanish translation jul23

- package.json
- scripts/build-scripts.mjs
- src/plugins/video-creator/backend/export.ts
- src/plugins/video-creator/backend/utils.ts
- src/plugins/video-creator/components/PreviewCarousel.less
No more "target same pixel ratio." Is "Upscale multiplier" a good name?
Fixes #326
> Video Creator tweaks

- src/plugins/intellisense/latex-parsing.tsx
> Intellisense: Backspace off-by-one error

- localization/es.ftl
Included the latest plugin into the spanish translations. This is already proof-read.
> Update Spanish translations

- src/plugins/show-tips/Tip.tsx
> Fixed bug where tips "Learn More" didn't update upon changing languagae.

- src/DCGView.ts
- src/components/desmosComponents.ts
- src/plugins/GLesmos/index.ts
- src/plugins/intellisense/view.tsx
- src/plugins/pillbox-menus/components/Menu.tsx
- src/plugins/pillbox-menus/index.ts
- src/plugins/show-tips/index.ts
- src/plugins/text-mode/index.ts
- src/plugins/video-creator/components/CaptureMethod.tsx
- Add a bunch of types where there previously weren't
- Use `Match` and `SwitchUnion` components where reasonable (instead of `Switch`).
> Improve typings for DCGView

- docs/CHANGELOG.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/chrome/net_request_rules.json
- public/firefox/manifest.json
- src/background.ts
- src/preload/script.ts
- Fix loading on /geometry
- Prepare v0.11.7
> Prepare v0.11.7

- src/preload/script.ts
Extremely basic PR, closes #607
> Add short message and splash in console

- README.md
Another tiny PR, added a single section to a link
> Fix broken link in README - Closes #619

- src/tests/setup-unit.js
- text-mode-core/tests/run_calc_for_tests.ts
- Re-download calculator_desktop if it's more than a day old
- Mock window.matchMedia
> Mock window.matchMedia in tests

- localization/en.ftl
- src/DCGView.ts
- src/plugins/code-golf/code-golf.replacements
- src/plugins/code-golf/config.ts
- src/plugins/code-golf/index.less
- src/plugins/code-golf/index.tsx
- src/plugins/index-replacements.ts
- src/plugins/index.ts
- src/plugins/pillbox-menus/components/Menu.tsx
- src/preload/moduleReplacements.ts
> Code Golf Plugin

- localization/es.ftl
I already read proofed this translation
> update spanish translation

- src/plugins/video-creator/backend/capture.ts
Fixes vertical stretch, mentioned in https://github.com/DesModder/DesModder/issues/754#issuecomment-1751646517
> Use sync screenshot for 3d capture

- docs/CHANGELOG.md
- package-lock.json
- package.json
- public/chrome/manifest.json
- public/firefox/manifest.json
- src/preload/moduleOverrides/insert-panels.replacements
- Fix "Insert Panels" replacement
- Prepare v0.12.4
> Prepare 0.12.4

- src/plugins/multiline/index.ts
> Prevent default Ctrl+M mute

- text-mode-core/aug/rawToAug.ts
> Fix empty table conversion to Text Mode

- graph-state/state.ts
- text-mode-core/aug/AugState.ts
- text-mode-core/aug/augToRaw.ts
- text-mode-core/aug/rawToAug.ts
- text-mode-core/down/astToAug.ts
- text-mode-core/down/style/Hydrated.ts
- text-mode-core/down/style/defaults.ts
- text-mode-core/down/style/schema.ts
- text-mode-core/up/augToAST.ts
For 3d parametrics/spherical/cylindrical.
> Support u,v,r,phi bounds

- package.json
- parsing/parsenode.ts
- parsing/traverse.ts
- src/plugins/builtin-settings/builtin-settings.int.test.ts
- src/plugins/text-mode/lezer/completions.ts
- text-mode-core/TextAST/index.ts
- Use --build instead of --noEmit
- Fix type errors
> Fix Typechecking

- src/preload/script.ts
> Block precisely pathname /geometry-legacy

- src/plugins/right-click-tray/right-click-tray.replacements
> Close existing tray before opening new one

- src/globals/Calc.ts
- src/plugins/performance-info/index.ts
> Add allowUndo to refreshState for performance-view

- src/plugins/pillbox-menus/components/Menu.less
- src/plugins/pillbox-menus/components/Menu.tsx
this issue basically https://github.com/DesModder/DesModder/issues/57
would look like this?
> show version number in the plugin menu

- src/globals/Calc.ts
- src/globals/window.ts
- src/plugins/video-creator/components/OrientationView.tsx
- src/plugins/video-creator/orientation.ts
- src/utils/depUtils.ts
> Fix Video Creator

- src/preload/script.ts
There's a race condition here, but this seems to catch some of Desmos loading despite DesModder.
> Check if Desmos is already loaded

- src/MainController.ts
- src/plugins/manage-metadata/index.ts
> Don't autodisable glesmos

- src/plugins/better-navigation/index.less
Fixes issue where mixed text / math fields would have the text offset vertically.
> Limit scrollability to editable fields

- localization/en.ftl
- localization/es.ftl
- localization/fr.ftl
- localization/ja.ftl
- localization/zh-CN.ftl
- src/plugins/builtin-settings/config.ts
- src/plugins/builtin-settings/index.ts
> Remove 3 settings and add "show IDs"

- .gitignore
> Git ignore .DS_Store files on macOS

- src/core-plugins/manage-metadata/manage-metadata.replacements
- src/plugins/better-evaluation-view/better-evaluation-view.replacements
Better evaluation had partially broken because of two replacements. This fixes the issue.
> Fix symbol replacement for better evaluation

- src/plugins/better-evaluation-view/better-evaluation-view.replacements
It fixes #942 (Complex numbers can't be shown with Better Evaluation View)
> Fix better evaluation for complex numbers

- src/plugins/code-golf/code-golf.replacements
Maintenance PR to fix the UI for code golf. The replacements to show the stats in each expressions broke.
> Fix broken replacements for code golf UI

- docs/PLUGINS.md
- src/globals/Calc.ts
- src/globals/models.ts
- src/plugins/intellisense/index.tsx
- src/plugins/intellisense/state.tsx
- src/plugins/intellisense/view.tsx
Fixes #947
Include intellisense for table exports and regression exports.
> Intellisense: Remove statements robustly, and handle tables and regressions

- .github/workflows/lint-and-test.yml
- package-lock.json
- package.json
Hoping that this magically fixes the ci integration test issues.
> Fix Github workflow failures

- src/plugins/compact-view/compact.less
> Unhide checked folder toggles

- localization/en.ftl
- src/plugins/builtin-settings/config.ts
- src/plugins/builtin-settings/index.ts
Not sure if this is the right place for this, may be better to put it in Performance Display.
> Add showPerformanceMeter to Calculator Settings

- src/plugins/builtin-settings/config.ts
- src/plugins/builtin-settings/index.ts
> Prevent softlock

- localization/en.ftl
- src/globals/Calc.ts
- src/plugins/video-creator/backend/capture.ts
- src/plugins/video-creator/backend/utils.ts
- src/plugins/video-creator/components/CaptureMethod.tsx
- src/plugins/video-creator/index.ts
- (NOPE) Avoid duplicate axes and stuff. (remember some images are behind axes)
- Just let the user disable axes if they want.
- (NOPE) <s>Share canvas across frames?</s>
- Probably not bottleneck, ignoring.
> Support mosaic in video creator

- src/plugins/better-evaluation-view/better-evaluation-view.replacements
- Added replacements for `list-count`
> Fix broken replacements for `Show list elements`

- src/plugins/GLesmos/glesmos.replacements
Fixed `_graphFunc` replacements
> Fix broken replacements for GLesmos

- src/plugins/better-evaluation-view/better-evaluation-view.replacements
Fixed replacements: `list-count`, `list` and `emptyList`
> Fix broken replacements for Better Evaluation View

- localization/ja.ftl
Added Japanese translation for `better-navigation-opt-showScrollbar-name` and `better-navigation-opt-showScrollbar-desc`.
> Sync Japanese localization

- src/plugins/syntax-highlighting/bracket-pair-colorization.ts
> Do not highlight inside a base case

- src/plugins/find-replace/find-replace.int.test.ts
- src/plugins/video-creator/video-creator.int.test.ts
- src/tests/puppeteer-utils.ts
- src/tests/setup-integration.js
- src/tests/testing.md
Fix find-replace on mac.
Add some more configuration to the tests without editing code.
> Improve some testing stuff

- apply-replacements/applyReplacement.ts
- jest-config/jest-base.config.js
- jest-config/replacements-transformer.mjs
- src/plugins/text-mode/modify.ts
- src/preload/moduleReplacements.ts
- src/preload/replacements.unit.test.ts
- src/preload/script.ts
- src/tests/smoke.int.test.ts
- text-mode-core/TextAST/Synthetic.ts
- text-mode-core/TextAST/index.ts
- text-mode-core/aug/AugState.ts
- text-mode-core/aug/augBuilders.ts
- text-mode-core/aug/augLatexToRaw.ts
- text-mode-core/aug/augNeedsParens.ts
- text-mode-core/aug/augToRaw.ts
- text-mode-core/aug/index.ts
- text-mode-core/aug/rawToAug.ts
- text-mode-core/down/astToAug.ts
- text-mode-core/down/diagnostics.ts
- text-mode-core/down/staticEval.ts
- text-mode-core/down/style/hydrate.ts
- text-mode-core/down/textToAST.ts
- text-mode-core/down/textToAug.unit.test.ts
- text-mode-core/up/astToText.ts
- text-mode-core/up/augToAST.ts
- text-mode-core/up/augToText.ts
- text-mode-core/up/augToText.unit.test.ts
- text-mode-core/up/rawToText.ts
- tsconfig-base.json
Smoke test inside puppeteer test that the [!] doesn't pop up.
Also some unit tests.
> Add tests for replacements

- src/plugins/code-golf/GolfStatsPanel.less
| Before | After |
| --- | --- |
| <img width="735" height="949" alt="before" src="https://github.com/user-attachments/assets/788631c8-dbc9-439c-b045-5a14ab8c2b13" /> | <img width="735" height="949" alt="after" src="https://github.com/user-attachments/assets/ea1830d5-0f3e-4233-8724-6b2c147039c6" /> |
> Place the golf panel under the evaluation dropdown

- src/globals/Calc.ts
- src/plugins/video-creator/backend/capture.ts
> Fix #1050 video creator mosaic
